List<Map<String, dynamic>> peopleProfile = [
  {
    "profileId": 1,
    "profilePhoto": "assets/images/people_photo1.png",
    "profileName": "zackjohn",
    "profileGender": "male",
    "storyUploaded": true,
    "liveMod": false,
  },
  {
    "profileId": 2,
    "profilePhoto": "assets/images/people_photo2.png",
    "profileName": "maxjacobson",
    "profileGender": "male",
    "storyUploaded": false,
    "liveMod": true,
  },
  {
    "profileId": 3,
    "profilePhoto": "assets/images/people_photo3.png",
    "profileName": "mis_potter",
    "profileGender": "female",
    "storyUploaded": false,
    "liveMod": true,
  },
  {
    "profileId": 4,
    "profilePhoto": "assets/images/people_photo4.png",
    "profileName": "joshua_l",
    "profileGender": "male",
    "storyUploaded": false,
    "liveMod": false,
  },
  {
    "profileId": 5,
    "profilePhoto": "assets/images/people_photo5.png",
    "profileName": "martini_rond",
    "profileGender": "male",
    "storyUploaded": false,
    "liveMod": false,
  },
  {
    "profileId": 6,
    "profilePhoto": "assets/images/people_photo6.png",
    "profileName": "kiero_d",
    "profileGender": "male",
    "storyUploaded": true,
    "liveMod": false,
  },
  {
    "profileId": 7,
    "profilePhoto": "assets/images/people_photo7.png",
    "profileName": "m_humphrey",
    "profileGender": "female",
    "storyUploaded": false,
    "liveMod": false,
  },
  {
    "profileId": 8,
    "profilePhoto": "assets/images/people_photo8.png",
    "profileName": "karennne",
    "profileGender": "female",
    "storyUploaded": true,
    "liveMod": true,
  },
  {
    "profileId": 9,
    "profilePhoto": "assets/images/people_photo9.png",
    "profileName": "andrewww_",
    "profileGender": "male",
    "storyUploaded": true,
    "liveMod": false,
  },
  {
    "profileId": 10,
    "profilePhoto": "assets/images/people_photo10.png",
    "profileName": "jamie.franco",
    "profileGender": "female",
    "storyUploaded": true,
    "liveMod": false,
  }
];
